"""Project-scoped permission codenames and human labels."""

PERMISSIONS: dict[str, str] = {
    'view_project': 'View project',
    'edit_project': 'Edit project',
    'manage_members': 'Manage members',
    'view_wbs': 'View WBS',
    'edit_wbs': 'Edit WBS',
    'view_activities': 'View activities',
    'edit_activities': 'Edit activities',
    'view_costs': 'View costs',
    'edit_costs': 'Edit costs',
    'approve_costs': 'Approve costs',
    'view_suppliers': 'View suppliers',
    'edit_suppliers': 'Edit suppliers',
    'view_reports': 'View reports',
    'edit_reports': 'Edit reports',
    'approve_reports': 'Approve reports',
    'view_contracts': 'View contracts',
    'edit_contracts': 'Edit contracts',
    'view_ipcs': 'View IPCs',
    'edit_ipcs': 'Edit IPCs',
    'approve_ipcs': 'Approve IPCs',
    'view_cashflow': 'View cash flow',
    'edit_cashflow': 'Edit cash flow',
    'view_procurement': 'View procurement',
    'edit_procurement': 'Edit procurement',
    'approve_procurement': 'Approve procurement',
    'view_documents': 'View documents',
    'upload_documents': 'Upload documents',
    'view_correspondence': 'View correspondence',
    'edit_correspondence': 'Edit correspondence',
    'view_dashboard': 'View dashboard',
}

ALL_PERMISSION_CODENAMES = frozenset(PERMISSIONS.keys())

DEFAULT_ROLE_PERMISSIONS: dict[str, list[str]] = {
    'project_manager': list(PERMISSIONS.keys()),
    'planning_engineer': [
        'view_project',
        'view_wbs',
        'edit_wbs',
        'view_activities',
        'edit_activities',
        'view_reports',
        'view_dashboard',
        'view_costs',
        'view_cashflow',
        'view_contracts',
    ],
    'site_supervisor': [
        'view_project',
        'view_wbs',
        'view_activities',
        'view_reports',
        'edit_reports',
        'view_procurement',
    ],
    'field_supervisor': [
        'view_project',
        'view_wbs',
        'view_activities',
        'view_reports',
        'edit_reports',
    ],
    'finance_manager': [
        'view_project',
        'view_costs',
        'edit_costs',
        'approve_costs',
        'view_suppliers',
        'edit_suppliers',
        'view_contracts',
        'edit_contracts',
        'view_ipcs',
        'edit_ipcs',
        'approve_ipcs',
        'view_cashflow',
        'edit_cashflow',
        'view_dashboard',
        'view_procurement',
        'approve_procurement',
    ],
    'procurement_officer': [
        'view_project',
        'view_costs',
        'view_suppliers',
        'edit_suppliers',
        'view_documents',
        'upload_documents',
        'view_procurement',
        'edit_procurement',
    ],
    'document_controller': [
        'view_project',
        'view_documents',
        'upload_documents',
        'view_correspondence',
        'edit_correspondence',
    ],
    'viewer': [
        'view_project',
        'view_wbs',
        'view_activities',
        'view_dashboard',
    ],
}

DEFAULT_ROLE_DESCRIPTIONS: dict[str, str] = {
    'project_manager': 'دسترسی کامل به همه ماژول‌های پروژه.',
    'planning_engineer': 'دسترسی به برنامه‌ریزی و زمان‌بندی.',
    'site_supervisor': 'گزارش‌گیری کارگاهی و پیگیری پیشرفت.',
    'field_supervisor': 'تیم میدان برای ثبت گزارش روزانه در موبایل/تبلت.',
    'finance_manager': 'مدیریت مالی و قراردادها.',
    'procurement_officer': 'تدارکات و بارگذاری اسناد.',
    'document_controller': 'مدیریت اسناد.',
    'viewer': 'دسترسی فقط‌خواندنی به داده‌های پروژه.',
}
