# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(blank=True, default='', max_length=60)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_baselines', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='projects.project')),
            ],
            options={
                'db_table': 'baseline_schedules',
            },
        ),
        migrations.CreateModel(
            name='BaselineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_finish', models.DateField(blank=True, null=True)),
                ('planned_duration', models.IntegerField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('planned_progress', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('total_float', models.IntegerField(blank=True, null=True)),
                ('free_float', models.IntegerField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_entries', to='projects.activity')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_activities', to='schedule.baselineschedule')),
            ],
            options={
                'db_table': 'baseline_activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('planned_progress', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('actual_progress', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cumulative_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('deviation', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='projects.activity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_progress',
                'unique_together': {('activity', 'report_date')},
            },
        ),
    ]
