# Generated by Django 4.2.11 on 2026-07-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_customer_decisions'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MspImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('replace_existing', models.BooleanField(default=False)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msp_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msp_import_jobs', to='projects.project')),
            ],
            options={
                'db_table': 'msp_import_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
