# Generated by Django 4.2.11 on 2026-07-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_sprint6_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activityprogress',
            name='actprogress_activity_date_idx',
        ),
    ]
