# Generated by Django 4.2.11 on 2026-08-21 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_p6importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p6importjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
