# Generated by Django 4.2.11 on 2026-10-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_schedule_baseline_gap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0007_alter_p6importjob_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineschedule',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineschedule',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baselineschedule',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_baselines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('work_monday', models.BooleanField(default=True)),
                ('work_tuesday', models.BooleanField(default=True)),
                ('work_wednesday', models.BooleanField(default=True)),
                ('work_thursday', models.BooleanField(default=True)),
                ('work_friday', models.BooleanField(default=True)),
                ('work_saturday', models.BooleanField(default=False)),
                ('work_sunday', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_calendars', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'working_calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('milestone_impact', models.TextField(blank=True, default='')),
                ('cost_impact', models.TextField(blank=True, default='')),
                ('contract_impact', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('base_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_as_base', to='schedule.baselineschedule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_change_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to='projects.project')),
                ('resulting_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_resulting', to='schedule.baselineschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_planned_start', models.DateField(blank=True, null=True)),
                ('proposed_planned_finish', models.DateField(blank=True, null=True)),
                ('proposed_duration_days', models.IntegerField(blank=True, null=True)),
                ('proposed_forecast_start', models.DateField(blank=True, null=True)),
                ('proposed_forecast_finish', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_items', to='projects.activity')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schedule.schedulechangerequest')),
            ],
            options={
                'db_table': 'schedule_change_items',
            },
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exception_date', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedule.workingcalendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_exceptions',
                'ordering': ['exception_date'],
            },
        ),
        migrations.AddField(
            model_name='baselineschedule',
            name='source_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_baselines', to='schedule.schedulechangerequest'),
        ),
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('calendar', 'exception_date'), name='unique_active_calendar_exception_date'),
        ),
    ]
