# Generated by Django 4.2.11 on 2026-10-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_project_registration'),
        ('master_data', '0011_project_registration_permissions'),
        ('schedule', '0009_baseline_audit_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMeasurementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('quantity', 'Quantity'), ('weighted_milestones', 'Weighted milestones'), ('evidence_percent', 'Evidence percent')], default='quantity', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('evidence_rules', models.TextField(blank=True, default='')),
                ('pending_change_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_definition', to='projects.activity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_measurement_definitions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_measurement_definitions',
            },
        ),
        migrations.CreateModel(
            name='PeriodReportFigure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=60)),
                ('label_key', models.CharField(max_length=120)),
                ('value', models.JSONField(blank=True, null=True)),
                ('value_status', models.CharField(choices=[('recorded', 'Recorded'), ('not_recorded', 'Not recorded')], default='not_recorded', max_length=20)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, default='', max_length=255)),
                ('source_approved', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period_report_figures',
                'ordering': ['section'],
            },
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='approved_progress',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='evidence_refs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='period_progress',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='technical_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='technical_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technically_approved_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectPeriodReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('superseded', 'Superseded')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_period_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_reports', to='projects.project')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='schedule.projectperiodreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_period_reports',
                'ordering': ['-period_start', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodReportFigureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_figure_overrides', to=settings.AUTH_USER_MODEL)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='schedule.periodreportfigure')),
            ],
            options={
                'db_table': 'period_report_figure_overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='periodreportfigure',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='schedule.projectperiodreport'),
        ),
        migrations.CreateModel(
            name='ActivityQuantityChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('new_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_changes', to='projects.activity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quantity_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_quantity_changes', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_quantity_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMeasurementVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('quantity', 'Quantity'), ('weighted_milestones', 'Weighted milestones'), ('evidence_percent', 'Evidence percent')], max_length=30)),
                ('basis_snapshot', models.JSONField(blank=True, default=dict)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_measurement_versions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schedule.activitymeasurementdefinition')),
            ],
            options={
                'db_table': 'activity_measurement_versions',
                'ordering': ['version_number'],
            },
        ),
        migrations.AddField(
            model_name='activitymeasurementdefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.activitymeasurementversion'),
        ),
        migrations.AddField(
            model_name='activitymeasurementdefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_definitions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='activitymeasurementdefinition',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_definitions', to='master_data.unit'),
        ),
        migrations.AddField(
            model_name='activitymeasurementdefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='measurement_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='schedule.activitymeasurementversion'),
        ),
        migrations.AddIndex(
            model_name='projectperiodreport',
            index=models.Index(fields=['project', 'kind', 'period_start', 'period_end'], name='ppr_project_kind_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitymeasurementversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version_number'), name='uniq_measurement_version_number'),
        ),
    ]
