# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('expected_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expected_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('confidence_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'cash_flow_forecasts',
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_date', models.DateField()),
                ('tx_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('is_forecast', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash_transactions',
            },
        ),
    ]
