# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_flow', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='cashflowforecast',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_forecasts', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflowforecast',
            unique_together={('project', 'month')},
        ),
    ]
