export const ROUTES = {
  INDEX: "routes/index.tsx",
  LOGIN: "routes/login.tsx",
  REGISTER: "routes/register.tsx",
  FORGOT_PASSWORD: "routes/forgot-password.tsx",
  RESET_PASSWORD: "routes/reset-password.tsx",
  AUTH_LAYOUT: "routes/_auth.tsx",
  PROTECTED_LAYOUT: "routes/_protected.tsx",
  HR_PROTECTED_LAYOUT: "routes/hr/_protected-human-resource.tsx",
  HR_HUB: "routes/hr/home.tsx",
  HR_JOB_POSITIONS: "routes/hr/job-positions.tsx",
  HOME: "routes/home.tsx",
  BUSINESS: "routes/business.tsx",
  BUSINESS_USERS: "routes/business-users.tsx",
  BUSINESS_JOB_POSITIONS: "routes/business-job-positions.tsx",
  BUSINESS_TABLE: "routes/business-table.tsx",
  BUSINESS_SETUP: "routes/business-setup.tsx",
  BUSINESS_CREATE: "routes/project-create-wizard.tsx",
  PROJECT_LIST: "routes/project-list.tsx",
  PROJECT_OVERVIEW: "routes/project-overview.tsx",
  PROJECT_WBS: "routes/project-wbs.tsx",
  PROJECT_ACTIVITIES: "routes/project-activities.tsx",
  PROJECT_MEMBERS: "routes/project-members.tsx",
  PROJECT_WEATHER: "routes/project-weather.tsx",
  PROJECT_PROGRESS: "routes/project-progress.tsx",
  PROJECT_COSTS: "routes/project-costs.tsx",
  PROJECT_MATERIAL_BALANCE: "routes/project-material-balance.tsx",
  PROJECT_PERSONNEL_SUMMARY: "routes/project-personnel-summary.tsx",
  PROJECT_ACTIVITY_LOG: "routes/project-activity-log.tsx",
  PROJECT_CASH_FLOW: "routes/project-cash-flow.tsx",
  PROJECT_CONTRACTS: "routes/project-contracts.tsx",
  PROJECT_SUBCONTRACTORS: "routes/project-subcontractors.tsx",
  PROJECT_DOCUMENTS: "routes/project-documents.tsx",
  PROJECT_BARRIERS: "routes/project-barriers.tsx",
  PROJECT_LABOR_CAMP: "routes/project-labor-camp.tsx",
  PROJECT_EQUIPMENT_LOG: "routes/project-equipment-log.tsx",
  PROJECT_MANPOWER: "routes/project-manpower.tsx",
  PROJECT_OVERTIME: "routes/project-overtime-requests.tsx",
  PROJECT_LEAVE: "routes/project-leave-requests.tsx",
  PROJECT_SUB_REPORTS: "routes/project-sub-reports.tsx",
  PROJECT_DAILY_REPORTS: "routes/daily-reports-list.tsx",
  PROJECT_DAILY_REPORT_NEW: "routes/daily-report-form.tsx",
  PROJECT_DAILY_REPORT_EDIT: "routes/daily-report-form-edit.tsx",
  PROJECT_DAILY_REPORT_VIEW: "routes/daily-report-view.tsx",
  PROJECT_SYNC_CONFLICTS: "routes/sync-conflicts.tsx",
  SETTINGS_TEMPLATES: "routes/settings-templates.tsx",
  SETTINGS_ROLES: "routes/settings-roles.tsx",
  BUSINESS_SETUP_SCHEMA: "routes/business-setup-schema.tsx",
  USERS: "routes/hr/users.tsx",
  BUSINESS_BUILDINGS: "routes/business-buildings.tsx",
  BUSINESS_MECHANICAL: "routes/business-mechanical.tsx",
  BUSINESS_SECURITY: "routes/business-security.tsx",
  BUSINESS_MACHINERY: "routes/business-machinery.tsx",
  BUSINESS_WAREHOUSE: "routes/business-warehouse.tsx",
  BUSINESS_ELECTRICAL: "routes/business-electrical.tsx",
} as const;

/** URL segments (no leading slash). */
export const PATHS = {
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  HOME: "home",
  /** Frontend URL segment `/projects/...`. */
  PROJECT: "projects",
  /** API base segment `v1/projects`. */
  API_PROJECTS: "v1/projects",
  /** @deprecated use PROJECT */
  BUSINESS: "projects",
  PROJECT_OVERVIEW: "overview",
  PROJECT_WBS: "wbs",
  PROJECT_ACTIVITIES: "activities",
  PROJECT_SETTINGS: "settings",
  PROJECT_MEMBERS: "members",
  PROJECT_WEATHER: "weather",
  PROJECT_PROGRESS: "progress",
  PROJECT_COSTS: "costs",
  PROJECT_MATERIAL_BALANCE: "material-balance",
  PROJECT_PERSONNEL_SUMMARY: "personnel-summary",
  PROJECT_ACTIVITY_LOG: "activity-log",
  PROJECT_CASH_FLOW: "cash-flow",
  PROJECT_CONTRACTS: "contracts",
  PROJECT_SUBCONTRACTORS: "subcontractors",
  PROJECT_DOCUMENTS: "documents",
  PROJECT_BARRIERS: "barriers",
  PROJECT_LABOR_CAMP: "labor-camp",
  PROJECT_EQUIPMENT_LOG: "equipment-log",
  PROJECT_MANPOWER: "manpower",
  PROJECT_OVERTIME: "overtime-requests",
  PROJECT_LEAVE: "leave-requests",
  PROJECT_SUB_REPORTS: "sub-reports",
  PROJECT_DAILY_REPORTS: "daily-reports",
  PROJECT_SYNC_CONFLICTS: "sync-conflicts",
  SETTINGS: "settings",
  SETTINGS_TEMPLATES: "templates",
  SETTINGS_ROLES: "roles",
  PROJECT_NEW: "new",
  /** @deprecated use PROJECT_NEW */
  BUSINESS_CREATE: "new",
  /** `/businesses/:id/setup` (tables & fields admin) */
  BUSINESS_ADMIN_SETUP: "setup",
  /** App HR area: `/hr` (hub) and `hr/...` sub-routes. */
  HR: "hr",
  HR_JOB_POSITIONS: "job-positions",
  USERS: "hr/users",
  /** `GET /api/auth/users/` — HR / admin user list (not a React route). */
  API_AUTH_USERS: "auth/users",
  /** Department segments under `/businesses/:id/...`. */
  BUSINESS_DEPT: {
    BUILDINGS: "buildings",
    MECHANICAL: "mechanical",
    SECURITY: "security",
    MACHINERY: "machinery",
    WAREHOUSE: "warehouse",
    ELECTRICAL: "electrical",
  },
} as const;
