import { route } from "@react-router/dev/routes";
import { PATHS, ROUTES } from "../routeVars";

export const projectRoutes = [
  route(`${PATHS.PROJECT}/${PATHS.PROJECT_NEW}`, ROUTES.BUSINESS_CREATE),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_OVERVIEW}`, ROUTES.PROJECT_OVERVIEW),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_WBS}`, ROUTES.PROJECT_WBS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_ACTIVITIES}`, ROUTES.PROJECT_ACTIVITIES),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SETTINGS}/${PATHS.PROJECT_MEMBERS}`,
    ROUTES.PROJECT_MEMBERS,
  ),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_WEATHER}`, ROUTES.PROJECT_WEATHER),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}`,
    ROUTES.PROJECT_DAILY_REPORTS,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/${PATHS.PROJECT_NEW}`,
    ROUTES.PROJECT_DAILY_REPORT_NEW,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/:reportId/edit`,
    ROUTES.PROJECT_DAILY_REPORT_EDIT,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/:reportId/view`,
    ROUTES.PROJECT_DAILY_REPORT_VIEW,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SYNC_CONFLICTS}`,
    ROUTES.PROJECT_SYNC_CONFLICTS,
  ),
  route(PATHS.PROJECT, ROUTES.PROJECT_LIST),
  route(`${PATHS.SETTINGS}/${PATHS.SETTINGS_TEMPLATES}`, ROUTES.SETTINGS_TEMPLATES),
  route(`${PATHS.SETTINGS}/${PATHS.SETTINGS_ROLES}`, ROUTES.SETTINGS_ROLES),
];
