import { route } from "@react-router/dev/routes";
import { PATHS, ROUTES } from "../routeVars";

export const projectRoutes = [
  route(`${PATHS.PROJECT}/${PATHS.PROJECT_NEW}`, ROUTES.BUSINESS_CREATE),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_OVERVIEW}`, ROUTES.PROJECT_OVERVIEW),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_WBS}`, ROUTES.PROJECT_WBS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_ACTIVITIES}`, ROUTES.PROJECT_ACTIVITIES),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SETTINGS}/${PATHS.PROJECT_MEMBERS}`,
    ROUTES.PROJECT_MEMBERS,
  ),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_WEATHER}`, ROUTES.PROJECT_WEATHER),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_PROGRESS}`, ROUTES.PROJECT_PROGRESS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_COSTS}`, ROUTES.PROJECT_COSTS),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_MATERIAL_BALANCE}`,
    ROUTES.PROJECT_MATERIAL_BALANCE,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_PERSONNEL_SUMMARY}`,
    ROUTES.PROJECT_PERSONNEL_SUMMARY,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_ACTIVITY_LOG}`,
    ROUTES.PROJECT_ACTIVITY_LOG,
  ),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_CASH_FLOW}`, ROUTES.PROJECT_CASH_FLOW),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_CONTRACTS}`, ROUTES.PROJECT_CONTRACTS),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_CONTRACTS}/${PATHS.PROJECT_NEW}`,
    ROUTES.PROJECT_CONTRACT_NEW,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_CONTRACTS}/:contractId`,
    ROUTES.PROJECT_CONTRACT_DETAIL,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_IPCS}/:ipcId`,
    ROUTES.PROJECT_IPC_DETAIL,
  ),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SUBCONTRACTORS}`, ROUTES.PROJECT_SUBCONTRACTORS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DOCUMENTS}`, ROUTES.PROJECT_DOCUMENTS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_BARRIERS}`, ROUTES.PROJECT_BARRIERS),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_LABOR_CAMP}`, ROUTES.PROJECT_LABOR_CAMP),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_EQUIPMENT_LOG}`, ROUTES.PROJECT_EQUIPMENT_LOG),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_MANPOWER}`, ROUTES.PROJECT_MANPOWER),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_OVERTIME}`, ROUTES.PROJECT_OVERTIME),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_LEAVE}`, ROUTES.PROJECT_LEAVE),
  route(`${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SUB_REPORTS}`, ROUTES.PROJECT_SUB_REPORTS),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}`,
    ROUTES.PROJECT_DAILY_REPORTS,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/${PATHS.PROJECT_NEW}`,
    ROUTES.PROJECT_DAILY_REPORT_NEW,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/:reportId/edit`,
    ROUTES.PROJECT_DAILY_REPORT_EDIT,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_DAILY_REPORTS}/:reportId/view`,
    ROUTES.PROJECT_DAILY_REPORT_VIEW,
  ),
  route(
    `${PATHS.PROJECT}/:projectId/${PATHS.PROJECT_SYNC_CONFLICTS}`,
    ROUTES.PROJECT_SYNC_CONFLICTS,
  ),
  route(PATHS.PROJECT, ROUTES.PROJECT_LIST),
  route(`${PATHS.SETTINGS}/${PATHS.SETTINGS_TEMPLATES}`, ROUTES.SETTINGS_TEMPLATES),
  route(`${PATHS.SETTINGS}/${PATHS.SETTINGS_ROLES}`, ROUTES.SETTINGS_ROLES),
];
