# Generated by Django 4.2.11 on 2026-10-09 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0006_payment_terms_ipc_amounts'),
        ('risk', '0005_fr_rsk_quality_hse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_project_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('workflow_type', models.CharField(choices=[('purchase_request', 'Purchase request'), ('ipc_approval', 'IPC approval'), ('payment_approval', 'Payment approval'), ('budget_change', 'Budget change'), ('schedule_change', 'Schedule change'), ('inspection_approval', 'Inspection approval'), ('custom', 'Custom')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject_type', models.CharField(max_length=60)),
                ('subject_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_stage_order', models.PositiveIntegerField(blank=True, null=True)),
                ('current_due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='projects.project')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stage_assignments', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_stage_assignments',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('approver_role', models.CharField(blank=True, default='', max_length=60)),
                ('approval_mode', models.CharField(choices=[('all', 'All'), ('any', 'Any')], default='any', max_length=10)),
                ('on_reject', models.CharField(choices=[('stop', 'Stop'), ('return_previous', 'Return previous'), ('return_to', 'Return to')], default='stop', max_length=20)),
                ('return_to_order', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notify_on_enter', models.BooleanField(default=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages_as_approver', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflow.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('start', 'Start'), ('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return'), ('cancel', 'Cancel'), ('comment', 'Comment')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('stage_order', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_action_logs', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_action_logs',
                'ordering': ['acted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.TextField()),
                ('options', models.TextField()),
                ('criteria', models.TextField()),
                ('final_decision', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('rationale', models.TextField()),
                ('attachment_refs', models.JSONField(blank=True, default=list)),
                ('impact_schedule', models.BooleanField(default=False)),
                ('impact_cost', models.BooleanField(default=False)),
                ('impact_contract', models.BooleanField(default=False)),
                ('impact_risk', models.BooleanField(default=False)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approvers', models.ManyToManyField(blank=True, related_name='decisions_to_approve', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('execution_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_decisions', to='projects.project')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_decisions', to=settings.AUTH_USER_MODEL)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_decisions', to='projects.activity')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_decisions', to='contracts.contract')),
                ('related_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_decisions', to='risk.riskevent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_decisions', to='workflow.workflowinstance')),
            ],
            options={
                'db_table': 'management_decisions',
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstageassignment',
            constraint=models.UniqueConstraint(fields=('instance', 'stage_order', 'assignee'), name='uniq_instance_stage_assignee'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('definition', 'order'), name='uniq_stage_order_per_def'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['project', 'status'], name='workflow_in_project_264915_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['subject_type', 'subject_id'], name='workflow_in_subject_b90914_idx'),
        ),
    ]
