# Generated by Django 4.2.11 on 2026-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcontractorwarning',
            name='warning_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('written', 'Written'), ('final', 'Final'), ('contract_suspension', 'Contract suspension')], max_length=30),
        ),
    ]
