# Generated by Django 4.2.11 on 2026-08-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0003_sprint9_procurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_activity_audit_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block_code', models.CharField(max_length=30)),
                ('block_name', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='projects.wbs')),
            ],
            options={
                'db_table': 'procurement_blocks',
            },
        ),
        migrations.CreateModel(
            name='RequisitionHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requisition_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('requisition_type', models.CharField(choices=[('planned', 'عادی (Planned)'), ('fast_track', 'فورسماژور (Fast-Track)'), ('post_facto', 'پسنگر (Post-Facto)')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('urgency', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'پیشنویس'), ('technical_review', 'بررسی فنی'), ('workshop_approval', 'تایید کارگاه'), ('control_check', 'کنترل پروژه'), ('pm_approval', 'تایید مدیر پروژه'), ('procurement_queue', 'صف تدارکات'), ('hq_control_approval', 'تایید دفتر مرکزی'), ('final_approval', 'تایید نهایی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='draft', max_length=30)),
                ('request_date', models.DateField()),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('is_grn_provisional', models.BooleanField(default=False, help_text='برای پسنگر: رسید انبار «موقت» تا تکمیل امضا')),
                ('notes', models.TextField(blank=True, default='')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='procurement.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_requested', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_requisitions',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField()),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('purchased_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('on_hold', 'در انتظار بودجه'), ('ordered', 'سفارش داده شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requisition_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.requisitionheader')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='resources.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='projects.wbs')),
            ],
            options={
                'db_table': 'procurement_requisition_items',
                'ordering': ['line_number'],
                'unique_together': {('header', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('mr_tag', models.CharField(help_text='[MR-ID]-[Block-ID] tag for block-level inventory tracing', max_length=120)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='procurement.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='resources.material')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.requisitionitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_inventory_allocations',
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('cost_adjustment_notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers', to='resources.material')),
                ('source_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='procurement.block')),
                ('target_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='procurement.block')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_internal_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_from', models.CharField(max_length=30)),
                ('step_to', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('approve', 'تایید'), ('reject', 'رد'), ('return', 'بازگشت')], max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='procurement.requisitionheader')),
            ],
            options={
                'db_table': 'procurement_approval_logs',
                'ordering': ['performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requisitionheader',
            index=models.Index(fields=['project', 'status'], name='req_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionheader',
            index=models.Index(fields=['block', 'status'], name='req_block_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['block', 'material'], name='alloc_block_material_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['mr_tag'], name='alloc_mr_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'block_code'), name='uniq_block_project_code'),
        ),
    ]
