# Generated by Django 4.2.11 on 2026-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_approval_log_create_partial_details'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_qty__gte', 0)), name='alloc_allocated_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(check=models.Q(('received_qty__gte', 0)), name='alloc_received_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(check=models.Q(('issued_qty__gte', 0)), name='alloc_issued_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(check=models.Q(('issued_qty__lte', models.F('received_qty'))), name='alloc_issued_lte_received'),
        ),
    ]
