# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, default='')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_log',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(blank=True, default='', max_length=60)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('condition', models.CharField(blank=True, choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('eq', 'Equal'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal')], default='', max_length=20)),
                ('recipient_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
    ]
