# Generated by Django 4.2.11 on 2026-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_log_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('ipc_payment_overdue', 'IPC payment overdue'), ('guarantee_expiring', 'Guarantee expiring'), ('budget_overrun', 'Budget overrun'), ('cash_gap_detected', 'Cash gap detected'), ('low_stock', 'Low stock'), ('activity_behind_schedule', 'Activity behind schedule'), ('missing_daily_report', 'Missing daily report'), ('daily_report_not_approved', 'Daily report not approved'), ('baseline_not_set', 'Baseline not set'), ('subcontractor_at_risk', 'Subcontractor at risk'), ('subcontractor_score_low', 'Subcontractor score low'), ('correspondence_response_due', 'Correspondence response due'), ('sync_conflict_unresolved', 'Sync conflict unresolved'), ('critical_path_delay', 'Critical path delay'), ('ipc_approval_delayed', 'IPC approval delayed'), ('procurement_overdue', 'Procurement overdue')], default='', max_length=60),
        ),
    ]
