# Generated by Django 4.2.11 on 2026-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='corr_type',
            field=models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming'), ('internal', 'Internal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('closed', 'Closed'), ('no_response_needed', 'No response needed')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_type',
            field=models.CharField(choices=[('weekly_progress', 'Weekly progress'), ('employer_meeting', 'Employer meeting'), ('subcontractor', 'Subcontractor'), ('safety', 'Safety'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('project', 'Project'), ('restricted', 'Restricted')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='doc_type',
            field=models.CharField(choices=[('drawing', 'Drawing'), ('specification', 'Specification'), ('contract', 'Contract'), ('report', 'Report'), ('correspondence', 'Correspondence'), ('minutes', 'Minutes'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
