# Generated by Django 4.2.11 on 2026-10-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_correspondence_related_contract_meetingminutes_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_code__gt', '')), fields=('project', 'doc_code'), name='uniq_project_document_doc_code_nonempty'),
        ),
    ]
