# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('contract_type', models.CharField(blank=True, default='', max_length=40)),
                ('counterparty', models.CharField(blank=True, default='', max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('advance_payment_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retention_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('insurance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('file_url', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boq_code', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'contract_items',
            },
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipc_number', models.IntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('prepared_date', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('planned_payment_date', models.DateField(blank=True, null=True)),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='contracts.contract')),
            ],
            options={
                'db_table': 'ipcs',
            },
        ),
        migrations.CreateModel(
            name='IPCItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_previous', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_current', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('qty_cumulative', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('amount_current', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_cumulative', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipc_items', to='contracts.contractitem')),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.ipc')),
            ],
            options={
                'db_table': 'ipc_items',
            },
        ),
        migrations.CreateModel(
            name='IPCDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('retention', 'Retention'), ('tax', 'Tax'), ('insurance', 'Insurance'), ('advance_recovery', 'Advance recovery'), ('material_price_diff', 'Material price diff'), ('other', 'Other')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='contracts.ipc')),
            ],
            options={
                'db_table': 'ipc_deductions',
            },
        ),
    ]
