# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('contracts', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='master_data.unit'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='ipc',
            unique_together={('project', 'contract', 'ipc_number')},
        ),
    ]
