# Generated by Django 4.2.11 on 2026-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_sprint7_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('subcontract', 'Subcontract'), ('purchase', 'Purchase'), ('equipment_rental', 'Equipment rental')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='draft', max_length=20),
        ),
    ]
