# Generated by Django 4.2.11 on 2026-10-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_central_data_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_alter_changeorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='master_data.managedcontracttype'),
        ),
        migrations.CreateModel(
            name='IPCCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('collected_at', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='contracts.ipc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ipc_collections',
                'ordering': ['collected_at', 'created_at'],
            },
        ),
    ]
