# Generated by Django 4.2.11 on 2026-07-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0004_seed_roles_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('road', 'Road'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('epc', 'EPC'), ('other', 'Other')], default='other', max_length=30)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_templates',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateWBS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wbs_code', models.CharField(max_length=30)),
                ('wbs_name', models.CharField(max_length=200)),
                ('weight_physical', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('level', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_templates.projecttemplatewbs')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_nodes', to='project_templates.projecttemplate')),
            ],
            options={
                'db_table': 'project_template_wbs',
                'ordering': ['level', 'order', 'wbs_code'],
                'unique_together': {('template', 'wbs_code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_code', models.CharField(max_length=30)),
                ('activity_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('template_wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project_templates.projecttemplatewbs')),
            ],
            options={
                'db_table': 'project_template_activities',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='master_data.role')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_roles', to='project_templates.projecttemplate')),
            ],
            options={
                'db_table': 'project_template_roles',
                'unique_together': {('template', 'role')},
            },
        ),
    ]
