# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('delay', 'Delay'), ('barrier', 'Barrier'), ('risk', 'Risk'), ('claim', 'Claim'), ('change_order', 'Change order')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('responsible_party', models.CharField(blank=True, default='', max_length=80)),
                ('time_impact_days', models.IntegerField(blank=True, null=True)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=10)),
                ('status', models.CharField(default='open', max_length=20)),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='projects.activity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risk_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='projects.project')),
            ],
            options={
                'db_table': 'risk_events',
            },
        ),
    ]
