# Generated by Django 4.2.11 on 2026-10-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def forwards_map_status(apps, schema_editor):
    RiskEvent = apps.get_model('risk', 'RiskEvent')
    RiskEvent.objects.filter(status='in_progress').update(status='under_review')
    RiskEvent.objects.filter(status='resolved').update(status='closed')


def backwards_map_status(apps, schema_editor):
    RiskEvent = apps.get_model('risk', 'RiskEvent')
    RiskEvent.objects.filter(status='under_review').update(status='in_progress')
    RiskEvent.objects.filter(status='closed').update(status='resolved')


class Migration(migrations.Migration):

    dependencies = [
        ('cost_control', '0007_cost_commitment_payment_gaps'),
        ('projects', '0012_project_registration'),
        ('contracts', '0006_payment_terms_ipc_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0004_claim_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_date', models.DateField()),
                ('stage', models.CharField(choices=[('plan', 'Plan'), ('request', 'Request'), ('result', 'Result')], default='result', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('pending', 'Pending')], default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='projects.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='projects.project')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_inspections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='projects.wbs')),
            ],
            options={
                'db_table': 'inspections',
            },
        ),
        migrations.AddField(
            model_name='riskevent',
            name='cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='composite_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='consequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_risk_events', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='cost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_risk_events', to='cost_control.costbreakdownnode'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='impact_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='impact_on_liquidity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='impact_on_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='impact_on_safety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='impact_severity_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='probability_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='related_decision_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='related_decision_ref',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='riskevent',
            name='event_type',
            field=models.CharField(choices=[('delay', 'Delay'), ('barrier', 'Barrier'), ('risk', 'Risk'), ('issue', 'Issue'), ('claim', 'Claim'), ('change_order', 'Change order')], max_length=20),
        ),
        migrations.RunPython(forwards_map_status, backwards_map_status),
        migrations.AlterField(
            model_name='riskevent',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('under_review', 'در بررسی'), ('mitigated', 'کاهش\u200cیافته'), ('closed', 'بسته'), ('residual', 'باقیمانده')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('permit_date', models.DateField()),
                ('permit_type', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permits', to='projects.project')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_permits', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_permits',
            },
        ),
        migrations.CreateModel(
            name='SafetyTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('training_date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('trainer_or_responsible', models.CharField(blank=True, default='', max_length=120)),
                ('attendees_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_trainings', to='projects.project')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_trainings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_trainings',
            },
        ),
        migrations.CreateModel(
            name='RiskAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risk_actions', to=settings.AUTH_USER_MODEL)),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='risk.riskevent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_actions',
            },
        ),
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('raised_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='risk.inspection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='projects.wbs')),
            ],
            options={
                'db_table': 'nonconformities',
            },
        ),
        migrations.CreateModel(
            name='HseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('incident', 'Incident'), ('near_miss', 'Near miss')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_events', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hse_events', to='projects.wbs')),
            ],
            options={
                'db_table': 'hse_events',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='risk.nonconformity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_corrective_actions', to='projects.project')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corrective_actions',
            },
        ),
    ]
