# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inflation_adj_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('financing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('accounting_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('real_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('economic_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('working_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg_payment_delay_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'economic_snapshots',
            },
        ),
        migrations.CreateModel(
            name='InflationIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_name', models.CharField(max_length=80)),
                ('index_date', models.DateField()),
                ('index_value', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'db_table': 'inflation_indices',
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('iterations', models.IntegerField(blank=True, null=True)),
                ('p10_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('p50_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('p90_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('prob_of_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('max_working_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sensitivity_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'simulation_results',
            },
        ),
    ]
