# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economic', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='inflationindex',
            unique_together={('index_name', 'index_date')},
        ),
        migrations.AddField(
            model_name='economicsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_snapshots', to='projects.project'),
        ),
    ]
