# Generated by Django 4.2.11 on 2026-02-21 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex=re.compile('^[a-z][a-z0-9_]*$'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex=re.compile('^[a-z][a-z0-9_]*$'))])),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('reference', 'Reference (FK to another table)')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['table', 'ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TableDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex=re.compile('^[a-z][a-z0-9_]*$'))])),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='business_meta.business')),
            ],
            options={
                'ordering': ['business', 'ordering', 'name'],
                'unique_together': {('business', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RelationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('one_to_many', 'One to many'), ('many_to_one', 'Many to one')], default='one_to_many', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_as_from', to='business_meta.fielddefinition')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='business_meta.tabledefinition')),
                ('to_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_as_to', to='business_meta.fielddefinition')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='business_meta.tabledefinition')),
            ],
            options={
                'ordering': ['from_table', 'to_table'],
            },
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='business_meta.tabledefinition'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='target_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_fields', to='business_meta.tabledefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('table', 'slug')},
        ),
    ]
