# Generated by Django 4.2.11 on 2026-06-25 12:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex=re.compile('^[a-z][a-z0-9_]*$'))])),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('reference', 'Reference (FK to another table)')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['table', 'ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RelationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('one_to_many', 'One to many'), ('many_to_one', 'Many to one')], default='one_to_many', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['from_table', 'to_table'],
            },
        ),
        migrations.CreateModel(
            name='TableDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex=re.compile('^[a-z][a-z0-9_]*$'))])),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project', 'ordering', 'name'],
            },
        ),
    ]
