# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('business_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='projects.project'),
        ),
        migrations.AddField(
            model_name='relationdefinition',
            name='from_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_as_from', to='business_meta.fielddefinition'),
        ),
        migrations.AddField(
            model_name='relationdefinition',
            name='from_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='business_meta.tabledefinition'),
        ),
        migrations.AddField(
            model_name='relationdefinition',
            name='to_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_as_to', to='business_meta.fielddefinition'),
        ),
        migrations.AddField(
            model_name='relationdefinition',
            name='to_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='business_meta.tabledefinition'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='business_meta.tabledefinition'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='target_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_fields', to='business_meta.tabledefinition'),
        ),
        migrations.AddField(
            model_name='dynamictablerow',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='business_meta.tabledefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='tabledefinition',
            unique_together={('project', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('table', 'slug')},
        ),
        migrations.AddIndex(
            model_name='dynamictablerow',
            index=models.Index(fields=['table'], name='business_me_table_i_54cfbf_idx'),
        ),
    ]
