# Generated by Django 4.2.11 on 2026-02-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='business_meta.tabledefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table'], name='business_me_table_i_54cfbf_idx')],
            },
        ),
    ]
