# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('buildings', 'ابنیه'), ('mechanical', 'مکانیک'), ('security', 'حراست'), ('machinery', 'ماشین آلات'), ('warehouse', 'انباردار'), ('electrical', 'برق')], db_index=True, max_length=32)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=500)),
                ('contractor', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField()),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.CharField(max_length=50)),
                ('space_name', models.CharField(max_length=255)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('technical_specs', models.TextField(blank=True, default='')),
                ('approved_quantity_technical_office', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('deliverable_quantity_inventory_unit', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
