# Generated by ChatGPT on 2026-04-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('business_meta', '0005_job_positions_and_user_assignment'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField()),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.CharField(max_length=50)),
                ('space_name', models.CharField(max_length=255)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('technical_specs', models.TextField(blank=True, default='')),
                ('approved_quantity_technical_office', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('deliverable_quantity_inventory_unit', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'business',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='space_material_requests',
                        to='business_meta.business',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spacematerialrequest',
            index=models.Index(fields=['business', 'material_code'], name='smr_business_material_idx'),
        ),
        migrations.AddIndex(
            model_name='spacematerialrequest',
            index=models.Index(fields=['business', 'block_number', 'floor_number'], name='smr_business_block_floor_idx'),
        ),
    ]

