# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacematerialrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_material_requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_activity_records', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='spacematerialrequest',
            index=models.Index(fields=['project', 'material_code'], name='smr_project_material_idx'),
        ),
        migrations.AddIndex(
            model_name='spacematerialrequest',
            index=models.Index(fields=['project', 'block_number', 'floor_number'], name='smr_project_block_floor_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentactivityrecord',
            index=models.Index(fields=['project', 'department', 'date'], name='dar_proj_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentactivityrecord',
            index=models.Index(fields=['project', 'department'], name='dar_proj_dept_idx'),
        ),
    ]
