# Generated by Cursor on 2026-05-08

from django.db import migrations, models
import django.db.models.deletion


# Class representing Migration
class Migration(migrations.Migration):
    dependencies = [
        ('business_meta', '0005_job_positions_and_user_assignment'),
        ('inventory', '0002_space_material_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'department',
                    models.CharField(
                        choices=[
                            ('buildings', 'ابنیه'),
                            ('mechanical', 'مکانیک'),
                            ('security', 'حراست'),
                            ('machinery', 'ماشین آلات'),
                            ('warehouse', 'انباردار'),
                            ('electrical', 'برق'),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=500)),
                ('contractor', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'business',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='department_activity_records',
                        to='business_meta.business',
                    ),
                ),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='departmentactivityrecord',
            index=models.Index(
                fields=['business', 'department', 'date'],
                name='dar_biz_dept_date_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='departmentactivityrecord',
            index=models.Index(
                fields=['business', 'department'],
                name='dar_biz_dept_idx',
            ),
        ),
    ]
