# Generated by Django 4.2.11 on 2026-10-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_departmentactivityrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='consumption_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='quantity_in',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='quantity_out',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='departmentactivityrecord',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='departmentactivityrecord',
            name='activity_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='departmentactivityrecord',
            name='contractor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='departmentactivityrecord',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
