# Generated by Django 4.2.11 on 2026-10-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0014_reportexportversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('selected_methods', models.JSONField(blank=True, default=list)),
                ('criteria', models.JSONField(blank=True, default=list)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('weights', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(blank=True, default=list)),
                ('performance_matrix', models.JSONField(blank=True, default=list)),
                ('ahp_matrix', models.JSONField(blank=True, default=list)),
                ('dematel_matrix', models.JSONField(blank=True, default=list)),
                ('ism_matrix', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cases', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=32)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('extracted_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='decision_support.decisioncase')),
                ('extracted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_runs', to='projects.project')),
            ],
            options={
                'db_table': 'decision_runs',
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['case', '-extracted_at'], name='decision_run_case_extracted'), models.Index(fields=['project', '-extracted_at'], name='decision_run_proj_extracted')],
            },
        ),
        migrations.AddIndex(
            model_name='decisioncase',
            index=models.Index(fields=['project', '-created_at'], name='decision_case_proj_created'),
        ),
    ]
