# Generated by Django 4.2.11 on 2026-06-25 12:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('wage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wage_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='hourly', max_length=20)),
                ('weekly_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_members',
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_member_roles',
            },
        ),
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator(message='Slug must start with a letter, then only lowercase letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'project_positions',
                'ordering': ['ordering', 'position_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=40)),
                ('unit_symbol', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'units',
            },
        ),
    ]
