# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_date', models.DateField()),
                ('cost_category', models.CharField(blank=True, choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('subcontract', 'Subcontract'), ('site_overhead', 'Site overhead'), ('hq_overhead', 'HQ overhead'), ('transport', 'Transport'), ('other', 'Other')], default='', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=60)),
                ('cost_type', models.CharField(choices=[('direct', 'Direct'), ('allocated_historical', 'Allocated historical'), ('estimated_historical', 'Estimated historical'), ('unallocated', 'Unallocated')], default='direct', max_length=20)),
                ('confidence_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=10)),
                ('allocation_method', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'actual_costs',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_category', models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('subcontract', 'Subcontract'), ('site_overhead', 'Site overhead'), ('hq_overhead', 'HQ overhead'), ('transport', 'Transport'), ('other', 'Other')], max_length=40)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='CostPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool_name', models.CharField(blank=True, default='', max_length=120)),
                ('cost_category', models.CharField(blank=True, choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('subcontract', 'Subcontract'), ('site_overhead', 'Site overhead'), ('hq_overhead', 'HQ overhead'), ('transport', 'Transport'), ('other', 'Other')], default='', max_length=40)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('unallocated', 'Unallocated'), ('partially_allocated', 'Partially allocated'), ('fully_allocated', 'Fully allocated')], default='unallocated', max_length=20)),
                ('data_source', models.CharField(blank=True, default='', max_length=60)),
                ('confidence_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=10)),
            ],
            options={
                'db_table': 'cost_pools',
            },
        ),
    ]
