# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('cost_control', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costpool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_pools', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budget',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budget',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.wbs'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_costs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='cost_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='cost_control.costpool'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_costs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='resources.supplier'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='projects.wbs'),
        ),
    ]
