# Generated by Django 4.2.11 on 2026-10-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_central_data_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_control', '0003_sprint6_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commitment_number', models.CharField(max_length=60)),
                ('counterparty', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('commitment_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('document_ref', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'db_table': 'commitments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('paid_at', models.DateField()),
                ('document_ref', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
                ('actual_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cost_control.actualcost')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cost_control.commitment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cost_payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='CostBreakdownNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('cbs_code', models.CharField(max_length=30)),
                ('cbs_name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(blank=True, choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('subcontract', 'Subcontract'), ('site_overhead', 'Site overhead'), ('hq_overhead', 'HQ overhead'), ('transport', 'Transport'), ('other', 'Other')], default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbs_nodes', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbs_nodes',
                'unique_together': {('project', 'cbs_code')},
            },
        ),
        migrations.AddField(
            model_name='commitment',
            name='cbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='cost_control.costbreakdownnode'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commitment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commitment',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='projects.wbs'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='cbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='cost_control.costbreakdownnode'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_costs', to='cost_control.commitment'),
        ),
        migrations.AddField(
            model_name='budget',
            name='cbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='cost_control.costbreakdownnode'),
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'commitment_number'), name='uniq_active_commitment_number'),
        ),
    ]
