# Generated by Django 4.2.11 on 2026-10-09 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_central_data_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_project_registration'),
        ('cost_control', '0004_central_data_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('project_impact', models.TextField()),
                ('affected_lines', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'budget_change_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'budget_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('initial', 'Initial'), ('approved', 'Approved'), ('revised', 'Revised'), ('final_forecast', 'Final forecast')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_control', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'budget_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='budget',
            name='level',
            field=models.CharField(choices=[('project', 'Project'), ('phase', 'Phase'), ('contract', 'Contract'), ('wbs', 'WBS package'), ('cbs', 'CBS'), ('activity', 'Activity')], default='wbs', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_versions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_versions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_versions_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_versions_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='from_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='cost_control.budget'),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_transfers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='to_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='cost_control.budget'),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cost_control.budgetversion'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='base_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='cost_control.budgetversion'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_change_requests_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_change_requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_change_requests_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='resulting_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_result', to='cost_control.budgetversion'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cost_control.budgetversion'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['version', 'cost_category'], name='budget_version_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'version_number'), name='uniq_active_budget_version_number'),
        ),
    ]
