# Generated by Django 4.2.11 on 2026-10-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_actual_cost_lifecycle(apps, schema_editor):
    ActualCost = apps.get_model('cost_control', 'ActualCost')
    for row in ActualCost.objects.all().iterator():
        updates = []
        if getattr(row, 'status', None) != 'approved':
            row.status = 'approved'
            updates.append('status')
        if row.registered_at is None and row.cost_date is not None:
            row.registered_at = row.cost_date
            updates.append('registered_at')
        if updates:
            row.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_inventory_stock_constraints'),
        ('contracts', '0006_payment_terms_ipc_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_control', '0006_attach_legacy_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcost',
            name='document_ref',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='registered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=20),
        ),
        migrations.RunPython(backfill_actual_cost_lifecycle, migrations.RunPython.noop),
        migrations.AddField(
            model_name='commitment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_commitments', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commitment',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='procurement.requisitionheader'),
        ),
        migrations.AddField(
            model_name='payment',
            name='duplicate_exception_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_duplicate_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='duplicate_exception_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
