# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=120)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_code', models.CharField(max_length=30, unique=True)),
                ('material_name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('min_stock_level', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='master_data.unit')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_date', models.DateField()),
                ('tx_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('waste', 'Waste'), ('adjust', 'Adjust')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('document_ref', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='projects.activity')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='resources.supplier')),
            ],
            options={
                'db_table': 'inventory_transactions',
            },
        ),
    ]
