# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_code', models.CharField(max_length=30)),
                ('activity_name', models.CharField(max_length=200)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_finish', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_finish', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='not_started', max_length=20)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=30, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('employer', models.CharField(blank=True, default='', max_length=120)),
                ('contractor', models.CharField(blank=True, default='', max_length=120)),
                ('consultant', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_type', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('handed_over', 'Handed over')], default='active', max_length=30)),
                ('cut_off_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wbs_code', models.CharField(max_length=30)),
                ('wbs_name', models.CharField(max_length=200)),
                ('level', models.SmallIntegerField()),
                ('weight_physical', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('weight_financial', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.wbs')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_nodes', to='projects.project')),
            ],
            options={
                'verbose_name': 'WBS',
                'verbose_name_plural': 'WBS',
                'db_table': 'wbs',
                'unique_together': {('project', 'wbs_code')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=4)),
                ('lag_days', models.IntegerField(default=0)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_relations', to='projects.activity')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_relations', to='projects.activity')),
            ],
            options={
                'db_table': 'activity_relations',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='master_data.unit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='wbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.wbs'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'activity_code')},
        ),
    ]
