# Generated by Django 4.2.11 on 2026-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_wbs_treebeard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_depth',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum WBS depth for this project. Null means unlimited.', null=True),
        ),
    ]
