# Generated by Django 4.2.11 on 2026-10-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_central_data_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_core_domain_principles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owning_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='master_data.organizationunit'),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('influence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('communication_need', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stakeholders',
                'ordering': ['name'],
            },
        ),
    ]
