# Generated by Django 4.2.11 on 2026-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_wbs_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='forecast_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='forecast_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
    ]
