# Generated by Django 4.2.11 on 2026-10-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_schedule_baseline_gap'),
        ('schedule', '0008_schedule_baseline_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='working_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schedule.workingcalendar'),
        ),
    ]
