# Generated by Django 4.2.11 on 2026-10-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_project_registration(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.filter(status='handed_over').update(status='completed')
    for project in Project.objects.filter(status='active', contract_amount__isnull=False, budget_approved_at__isnull=True):
        project.budget_approved_at = project.created_at
        project.save(update_fields=['budget_approved_at'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_schedule_baseline_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'project_change_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectKickoffCharter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('success_criteria', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('assumptions', models.TextField(blank=True, default='')),
                ('key_stakeholders_summary', models.TextField(blank=True, default='')),
                ('pm_authority', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'project_kickoff_charters',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='budget_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approved_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='main_deliverables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('archived', 'Archived'), ('handed_over', 'Handed over')], default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_idx'),
        ),
        migrations.AddField(
            model_name='projectkickoffcharter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectkickoffcharter',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff_charter', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectkickoffcharter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_change_requests_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_change_requests_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_project_registration, migrations.RunPython.noop),
    ]
