# Generated by Django 4.2.11 on 2026-10-09 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_stakeholder_relationship_owner_communicationplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(max_length=64)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField()),
                ('approved_only', models.BooleanField(default=True)),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('payload_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('extracted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='projects.project')),
            ],
            options={
                'db_table': 'report_export_versions',
                'ordering': ['-extracted_at'],
            },
        ),
    ]
