entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "www.toop-e-ghelgheli-2.ir"
            sans:
              - "toop-e-ghelgheli-2.ir"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@toop-e-ghelgheli-2.ir
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
