/**
 * Design system color tokens.
 * CSS variables are the source of truth; use these names in Tailwind (`bg-primary`)
 * or reference `palette` / `semantic` for programmatic styling.
 */

// Variable holding palette
export const palette = {
  brand: {
    50: "var(--palette-brand-50)",
    100: "var(--palette-brand-100)",
    200: "var(--palette-brand-200)",
    300: "var(--palette-brand-300)",
    400: "var(--palette-brand-400)",
    500: "var(--palette-brand-500)",
    600: "var(--palette-brand-600)",
    700: "var(--palette-brand-700)",
    800: "var(--palette-brand-800)",
    900: "var(--palette-brand-900)",
    950: "var(--palette-brand-950)",
  },
  accent: {
    50: "var(--palette-accent-50)",
    100: "var(--palette-accent-100)",
    200: "var(--palette-accent-200)",
    300: "var(--palette-accent-300)",
    400: "var(--palette-accent-400)",
    500: "var(--palette-accent-500)",
    600: "var(--palette-accent-600)",
    700: "var(--palette-accent-700)",
    800: "var(--palette-accent-800)",
    900: "var(--palette-accent-900)",
    950: "var(--palette-accent-950)",
  },
  neutral: {
    0: "var(--palette-neutral-0)",
    50: "var(--palette-neutral-50)",
    100: "var(--palette-neutral-100)",
    200: "var(--palette-neutral-200)",
    300: "var(--palette-neutral-300)",
    400: "var(--palette-neutral-400)",
    500: "var(--palette-neutral-500)",
    600: "var(--palette-neutral-600)",
    700: "var(--palette-neutral-700)",
    800: "var(--palette-neutral-800)",
    900: "var(--palette-neutral-900)",
    950: "var(--palette-neutral-950)",
  },
  success: {
    50: "var(--palette-success-50)",
    100: "var(--palette-success-100)",
    200: "var(--palette-success-200)",
    300: "var(--palette-success-300)",
    400: "var(--palette-success-400)",
    500: "var(--palette-success-500)",
    600: "var(--palette-success-600)",
    700: "var(--palette-success-700)",
    800: "var(--palette-success-800)",
    900: "var(--palette-success-900)",
    950: "var(--palette-success-950)",
  },
  warning: {
    50: "var(--palette-warning-50)",
    100: "var(--palette-warning-100)",
    200: "var(--palette-warning-200)",
    300: "var(--palette-warning-300)",
    400: "var(--palette-warning-400)",
    500: "var(--palette-warning-500)",
    600: "var(--palette-warning-600)",
    700: "var(--palette-warning-700)",
    800: "var(--palette-warning-800)",
    900: "var(--palette-warning-900)",
    950: "var(--palette-warning-950)",
  },
  danger: {
    50: "var(--palette-danger-50)",
    100: "var(--palette-danger-100)",
    200: "var(--palette-danger-200)",
    300: "var(--palette-danger-300)",
    400: "var(--palette-danger-400)",
    500: "var(--palette-danger-500)",
    600: "var(--palette-danger-600)",
    700: "var(--palette-danger-700)",
    800: "var(--palette-danger-800)",
    900: "var(--palette-danger-900)",
    950: "var(--palette-danger-950)",
  },
  info: {
    50: "var(--palette-info-50)",
    100: "var(--palette-info-100)",
    200: "var(--palette-info-200)",
    300: "var(--palette-info-300)",
    400: "var(--palette-info-400)",
    500: "var(--palette-info-500)",
    600: "var(--palette-info-600)",
    700: "var(--palette-info-700)",
    800: "var(--palette-info-800)",
    900: "var(--palette-info-900)",
    950: "var(--palette-info-950)",
  },
} as const;

/** Semantic tokens mapped in app.css — use via Tailwind utilities. */
// Variable holding semantic
export const semantic = {
  background: "var(--background)",
  foreground: "var(--foreground)",
  card: "var(--card)",
  cardForeground: "var(--card-foreground)",
  popover: "var(--popover)",
  popoverForeground: "var(--popover-foreground)",
  primary: "var(--primary)",
  primaryForeground: "var(--primary-foreground)",
  secondary: "var(--secondary)",
  secondaryForeground: "var(--secondary-foreground)",
  muted: "var(--muted)",
  mutedForeground: "var(--muted-foreground)",
  accent: "var(--accent)",
  accentForeground: "var(--accent-foreground)",
  destructive: "var(--destructive)",
  destructiveForeground: "var(--destructive-foreground)",
  success: "var(--success)",
  successForeground: "var(--success-foreground)",
  warning: "var(--warning)",
  warningForeground: "var(--warning-foreground)",
  info: "var(--info)",
  infoForeground: "var(--info-foreground)",
  border: "var(--border)",
  input: "var(--input)",
  ring: "var(--ring)",
  overlay: "var(--overlay)",
  surface: "var(--surface)",
} as const;

export type PaletteScale = keyof typeof palette;
export type PaletteStep = keyof (typeof palette)["brand"];
