# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_front', models.CharField(blank=True, default='', max_length=120)),
                ('executed_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'daily_activities',
            },
        ),
        migrations.CreateModel(
            name='DailyEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(blank=True, default='', max_length=80)),
                ('equipment_code', models.CharField(blank=True, default='', max_length=30)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('idle_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('idle_reason', models.TextField(blank=True, default='')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'daily_equipment',
            },
        ),
        migrations.CreateModel(
            name='DailyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('safety', 'Safety'), ('quality', 'Quality'), ('environmental', 'Environmental'), ('stoppage', 'Stoppage'), ('visitor', 'Visitor')], max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'daily_incidents',
            },
        ),
        migrations.CreateModel(
            name='DailyLabor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_type', models.CharField(blank=True, default='', max_length=60)),
                ('discipline', models.CharField(blank=True, default='', max_length=60)),
                ('headcount', models.IntegerField(blank=True, null=True)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'daily_labor',
            },
        ),
        migrations.CreateModel(
            name='DailyMaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'daily_material_usage',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full', 'Full')], default='full', max_length=10)),
                ('weather', models.CharField(blank=True, default='', max_length=40)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('general_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('synced_from_offline', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_daily_reports', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_reports',
            },
        ),
    ]
