# Generated by Django 4.2.11 on 2026-07-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_activity_audit_soft_delete'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full', 'Full')], default='full', max_length=10)),
                ('weather_condition', models.CharField(blank=True, choices=[('sunny', 'آفتابی'), ('cloudy', 'ابری'), ('partly_cloudy', 'نیمه\u200cابری'), ('rainy', 'بارانی'), ('stormy', 'طوفانی'), ('snowy', 'برفی'), ('foggy', 'مه\u200cآلود')], max_length=20, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('site_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10)),
                ('general_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_from_offline', models.BooleanField(default=False)),
                ('local_id', models.CharField(blank=True, max_length=36, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('log_date', models.DateField()),
                ('day_of_week', models.CharField(blank=True, default='', max_length=20)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weather_condition', models.CharField(choices=[('sunny', 'آفتابی'), ('cloudy', 'ابری'), ('partly_cloudy', 'نیمه\u200cابری'), ('rainy', 'بارانی'), ('stormy', 'طوفانی'), ('snowy', 'برفی'), ('foggy', 'مه\u200cآلود')], max_length=20)),
                ('site_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_logs',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='LaborJobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('indirect', 'ستادی'), ('direct', 'اجرایی')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'labor_job_titles',
                'ordering': ['category', 'display_order'],
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.CreateModel(
            name='DailyReportMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('material_description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=40)),
                ('transaction_type', models.CharField(choices=[('receipt', 'وارده'), ('issue', 'مصرف شده'), ('waste', 'ضایعات')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_materials', to='projects.activity')),
                ('material_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_materials', to='resources.material')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_entries', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_materials',
            },
        ),
        migrations.CreateModel(
            name='DailyReportLaborCamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('connex_number', models.CharField(max_length=60)),
                ('subcontractor_name', models.CharField(max_length=120)),
                ('total_residents', models.PositiveIntegerField()),
                ('present_count', models.PositiveIntegerField()),
                ('on_leave_count', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_camp_entries', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_labor_camp',
            },
        ),
        migrations.CreateModel(
            name='DailyReportLabor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('labor_category', models.CharField(choices=[('indirect', 'ستادی'), ('direct', 'اجرایی')], max_length=10)),
                ('job_title', models.CharField(max_length=120)),
                ('custom_title', models.CharField(blank=True, default='', max_length=120)),
                ('shift_1_count', models.PositiveIntegerField(default=0)),
                ('shift_2_count', models.PositiveIntegerField(default=0)),
                ('shift_3_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_labor',
            },
        ),
        migrations.CreateModel(
            name='DailyReportIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident_type', models.CharField(choices=[('safety', 'Safety'), ('quality', 'Quality'), ('environmental', 'Environmental'), ('stoppage', 'Stoppage'), ('visitor', 'Visitor')], max_length=40)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_incidents',
            },
        ),
        migrations.CreateModel(
            name='DailyReportEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_name', models.CharField(max_length=120)),
                ('equipment_ref', models.CharField(blank=True, default='', max_length=60)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full', 'Full')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('standby', 'آماده'), ('broken', 'خراب')], max_length=10)),
                ('ownership_type', models.CharField(choices=[('owned', 'تملیکی'), ('rented', 'اجاره\u200cای')], max_length=10)),
                ('work_start', models.TimeField(blank=True, null=True)),
                ('work_end', models.TimeField(blank=True, null=True)),
                ('repair_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('productive_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_equipment', to='projects.activity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_entries', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_equipment',
            },
        ),
        migrations.CreateModel(
            name='DailyReportConcreteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('concrete_description', models.CharField(max_length=120)),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('zone', models.CharField(blank=True, max_length=60, null=True)),
                ('block', models.CharField(blank=True, max_length=60, null=True)),
                ('floor', models.CharField(blank=True, max_length=60, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_concrete_logs', to='projects.activity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_logs', to='field_reports.dailyreport')),
            ],
            options={
                'db_table': 'daily_report_concrete_logs',
            },
        ),
        migrations.CreateModel(
            name='DailyReportActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_description', models.TextField()),
                ('shift', models.CharField(choices=[('shift_1', 'شیفت ۱'), ('shift_2', 'شیفت ۲'), ('shift_3', 'شیفت ۳')], max_length=10)),
                ('subcontractor_name', models.CharField(blank=True, default='', max_length=120)),
                ('headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=60, null=True)),
                ('block', models.CharField(blank=True, max_length=60, null=True)),
                ('floor', models.CharField(blank=True, max_length=60, null=True)),
                ('location_detail', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_measured', models.BooleanField(default=True)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('execution_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_activities', to='projects.activity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='field_reports.dailyreport')),
                ('subcontractor_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_activities', to='contracts.contract')),
            ],
            options={
                'db_table': 'daily_report_activities',
            },
        ),
        migrations.AddConstraint(
            model_name='weatherlog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'log_date'), name='unique_active_weather_log_per_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportlabor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report', 'labor_category', 'job_title'), name='unique_active_labor_row'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'report_date'), name='unique_active_daily_report_per_date'),
        ),
    ]
