# Generated by Django 4.2.11 on 2026-06-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('field_reports', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dailymaterialusage',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_material_usage', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='dailymaterialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='resources.material'),
        ),
        migrations.AddField(
            model_name='dailymaterialusage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usage', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailylabor',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_labor', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='dailylabor',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyincident',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyequipment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_equipment', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='dailyequipment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_equipment_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyequipment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_entries', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='field_reports.dailyreport'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('project', 'report_date', 'shift')},
        ),
    ]
