# Generated by Django 4.2.11 on 2026-07-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_wbs_treebeard'),
        ('field_reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField()),
                ('day_of_week', models.CharField(blank=True, default='', max_length=20)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weather_condition', models.CharField(choices=[('sunny', 'آفتابی'), ('cloudy', 'ابری'), ('partly_cloudy', 'نیمه\u200cابری'), ('rainy', 'بارانی'), ('stormy', 'طوفانی'), ('snowy', 'برفی'), ('foggy', 'مه\u200cآلود')], max_length=20)),
                ('site_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_logs',
                'ordering': ['-log_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='weatherlog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'log_date'), name='unique_active_weather_log_per_date'),
        ),
    ]
