# Generated by Django 4.2.11 on 2026-07-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_reports', '0006_sprint6_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyreport',
            name='dailyreport_project_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherlog',
            name='weatherlog_project_date_idx',
        ),
    ]
