# Generated by Django 4.2.11 on 2026-07-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_activity_audit_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_reports', '0010_shiraz_labor_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportequipment',
            name='idle_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportequipment',
            name='idle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreportlabor',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportlabor',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='idle_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='idle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_code', models.CharField(max_length=30)),
                ('equipment_name', models.CharField(max_length=120)),
                ('equipment_type', models.CharField(blank=True, default='', max_length=80)),
                ('ownership_type', models.CharField(choices=[('owned', 'تملیکی'), ('rented', 'اجاره\u200cای')], default='owned', max_length=10)),
                ('plate_number', models.CharField(blank=True, default='', max_length=30)),
                ('default_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_registry', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_registry',
                'ordering': ['equipment_name'],
            },
        ),
        migrations.AddField(
            model_name='dailyreportequipment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_entries', to='field_reports.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='field_reports.equipment'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('project', 'equipment_code'), name='uniq_equipment_project_code'),
        ),
    ]
