# Generated by Django 4.2.11 on 2026-07-20 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_activity_audit_soft_delete'),
        ('field_reports', '0012_unique_report_per_date_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_id', models.CharField(blank=True, default='', max_length=64)),
                ('conflict_reason', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflict_logs', to='field_reports.dailyreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflict_logs', to='projects.project')),
            ],
            options={
                'db_table': 'sync_conflict_logs',
                'indexes': [models.Index(fields=['project', 'resolved_at'], name='synclog_project_resolved_idx')],
            },
        ),
    ]
