# Generated by Django 4.2.11 on 2026-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_reports', '0013_sprint9_procurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlog',
            name='soil_condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='wind_speed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
