# Generated by Django 4.2.11 on 2026-10-08 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_lineage_id(apps, schema_editor):
    DailyReport = apps.get_model('field_reports', 'DailyReport')
    for report in DailyReport.objects.filter(lineage_id__isnull=True).iterator():
        DailyReport.objects.filter(pk=report.pk).update(lineage_id=report.id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_schedule_baseline_gap'),
        ('field_reports', '0014_weatherlog_soil_condition_weatherlog_wind_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'daily_report_correction_requests',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailyreport',
            name='unique_active_daily_report_per_date_shift',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='location_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_reports', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_front',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dailyreportactivity',
            name='responsible_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dailyreportactivity',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_activity_responsibilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportincident',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportincident',
            name='follow_up_owner_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dailyreportincident',
            name='follow_up_owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_incident_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportlabor',
            name='absence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportmaterial',
            name='consumption_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='dailyreportincident',
            name='incident_type',
            field=models.CharField(choices=[('safety', 'Safety'), ('quality', 'Quality'), ('environmental', 'Environmental'), ('stoppage', 'Stoppage'), ('visitor', 'Visitor'), ('site_instruction', 'Site instruction'), ('barrier', 'Barrier')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dailyreportmaterial',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'وارده'), ('issue', 'مصرف شده'), ('waste', 'ضایعات'), ('return', 'برگشتی')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_deleted', False)), fields=('project', 'report_date', 'shift'), name='unique_current_daily_report_per_date_shift'),
        ),
        migrations.RunPython(backfill_lineage_id, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_corrections_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_correction_requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_corrections_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='result_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_as_result', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='source_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests_as_source', to='field_reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailyreportcorrectionrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
